// <auto-generated />
using System;
using DotnetCourse.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetCourse.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20230118124145_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotnetCourse.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7fbb982-0c73-4ab6-9e81-95100132f4cf"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 371m,
                            Rating = 3.9375722541715366
                        },
                        new
                        {
                            Id = new Guid("8e189002-a661-4255-a234-cfd61770f820"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Mandarin Hotel",
                            Price = 440m,
                            Rating = 1.6360086270501677
                        },
                        new
                        {
                            Id = new Guid("c20af97a-ffc9-4086-ba4e-4f77883ea9ed"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 430m,
                            Rating = 4.4256072248646108
                        },
                        new
                        {
                            Id = new Guid("e2701f19-c1c0-4a0b-aac2-58a809774a16"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 398m,
                            Rating = 3.7871473058479808
                        },
                        new
                        {
                            Id = new Guid("cd6e4c8f-8cdf-4875-8107-6dac28cf93ce"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 329m,
                            Rating = 1.7967318522350673
                        },
                        new
                        {
                            Id = new Guid("2139430d-8caa-4733-9d27-2045ad708387"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Le Meridien Hotel",
                            Price = 468m,
                            Rating = 3.4578365070147314
                        },
                        new
                        {
                            Id = new Guid("feafb570-d946-4a00-9440-26b1d98af8a8"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "Grand Hotel",
                            Price = 440m,
                            Rating = 3.7008693838653466
                        },
                        new
                        {
                            Id = new Guid("e7e7a59c-1597-4beb-a05b-4f7869e512ac"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Westin Hotel",
                            Price = 114m,
                            Rating = 3.2249690868565937
                        },
                        new
                        {
                            Id = new Guid("6a487b8e-2742-41b8-9d02-fce250f8a8d8"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Crowne Plaza Hotel",
                            Price = 330m,
                            Rating = 4.6958129591951945
                        },
                        new
                        {
                            Id = new Guid("b4649f28-a73b-4b97-97a0-6414168c76de"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The St. Regis Hotel",
                            Price = 330m,
                            Rating = 2.4812646535635889
                        },
                        new
                        {
                            Id = new Guid("77901e92-f384-44bb-80bc-fc40c77b97a0"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Belmond Hotel",
                            Price = 204m,
                            Rating = 3.735211276038247
                        },
                        new
                        {
                            Id = new Guid("45afebad-9624-4e2b-8594-18b059cec920"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "Marriott Hotel",
                            Price = 296m,
                            Rating = 1.5512670443505043
                        },
                        new
                        {
                            Id = new Guid("4b80eda2-4959-43fb-8f26-798a6c26f203"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Shangri-La Hotel",
                            Price = 167m,
                            Rating = 2.2354370781512527
                        },
                        new
                        {
                            Id = new Guid("67733825-37e5-4c24-96ce-5d9e83f2dee4"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Shangri-La Hotel",
                            Price = 293m,
                            Rating = 3.6361978234664409
                        },
                        new
                        {
                            Id = new Guid("6ee24d2b-1372-483d-a762-b3c746486a4e"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Plaza",
                            Price = 380m,
                            Rating = 1.0249065250666289
                        },
                        new
                        {
                            Id = new Guid("37cb8cba-3a9f-4210-b416-94413641c7b8"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Belmond Hotel",
                            Price = 381m,
                            Rating = 0.32465728363133384
                        },
                        new
                        {
                            Id = new Guid("1d77138c-b61a-48d5-a09c-14a89b48815f"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 399m,
                            Rating = 4.4430327052175622
                        },
                        new
                        {
                            Id = new Guid("983b5d89-7b34-4a0f-9398-2d332db2c593"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Crowne Plaza Hotel",
                            Price = 131m,
                            Rating = 3.48427576573952
                        },
                        new
                        {
                            Id = new Guid("9bb8750a-fb7c-41f5-a0a1-4f7756a5024d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Belmond Hotel",
                            Price = 491m,
                            Rating = 1.0902490111213181
                        },
                        new
                        {
                            Id = new Guid("4ac6bcbc-cdc1-4bf6-bd5b-25a90f6af902"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "InterContinental Hotel",
                            Price = 236m,
                            Rating = 0.19371283242591131
                        },
                        new
                        {
                            Id = new Guid("ac50fd8f-3278-4103-bad7-a3ffec3c8c1a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Four Seasons Hotel",
                            Price = 148m,
                            Rating = 1.7409405746732216
                        },
                        new
                        {
                            Id = new Guid("7bfd4983-7144-4bb7-88d2-de8b03a2164c"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "Marriott Hotel",
                            Price = 481m,
                            Rating = 0.04668487385506348
                        },
                        new
                        {
                            Id = new Guid("de3911c1-2262-481d-8c56-536c47fada5a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Plaza",
                            Price = 278m,
                            Rating = 0.34448340340057171
                        },
                        new
                        {
                            Id = new Guid("2eabeecf-9bd1-45b0-97f5-4ae3b4d69d64"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Grand Hotel",
                            Price = 349m,
                            Rating = 3.2634150561536792
                        },
                        new
                        {
                            Id = new Guid("37caa274-f401-4b10-b027-ff8beaf4742d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 130m,
                            Rating = 2.96608136636931
                        },
                        new
                        {
                            Id = new Guid("727d50da-3c0c-4433-9139-7aecb94bf965"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "Hotel Ritz",
                            Price = 132m,
                            Rating = 0.14880170663821302
                        },
                        new
                        {
                            Id = new Guid("c5720a1e-8af5-49d0-81e9-8582ef8b9bba"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Hyatt Hotel",
                            Price = 497m,
                            Rating = 0.81827211656685106
                        },
                        new
                        {
                            Id = new Guid("50a1665d-18bd-468f-9262-294fd7bddd9c"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 196m,
                            Rating = 0.73238405437384579
                        },
                        new
                        {
                            Id = new Guid("7f0bc9ae-ad2f-4b08-b52f-c2cd924a0c91"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Waldorf Astoria Hotel",
                            Price = 402m,
                            Rating = 1.3972875254402113
                        },
                        new
                        {
                            Id = new Guid("af51c8f4-447a-4d33-a76a-0c7410bfb9d9"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "Sheraton Hotel",
                            Price = 322m,
                            Rating = 1.376245053522176
                        },
                        new
                        {
                            Id = new Guid("0c3f1e93-6572-4878-af98-5ff8edc06c50"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Mandarin Oriental Hotel",
                            Price = 447m,
                            Rating = 2.7363551782760425
                        },
                        new
                        {
                            Id = new Guid("2cd098c0-e3c8-49b4-a99f-4aecaa4657d0"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "W Hotels",
                            Price = 160m,
                            Rating = 3.8055630115266483
                        },
                        new
                        {
                            Id = new Guid("f413d279-af4b-474d-9700-f534164c1499"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Sheraton Hotel",
                            Price = 240m,
                            Rating = 2.965560630854883
                        },
                        new
                        {
                            Id = new Guid("6230748e-31d8-4590-8ea4-d48d5123f7aa"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Aman Hotel",
                            Price = 400m,
                            Rating = 0.7659330227718808
                        },
                        new
                        {
                            Id = new Guid("7d55363e-8ab4-43e0-b5ea-b8fde8196fdc"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Belmond Hotel",
                            Price = 445m,
                            Rating = 2.6758687757048167
                        },
                        new
                        {
                            Id = new Guid("80b56c2b-8df1-47d3-9e1b-2b28f88af0e4"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Belmond Hotel",
                            Price = 406m,
                            Rating = 4.8074682575738068
                        },
                        new
                        {
                            Id = new Guid("4aa832f6-1f4d-4554-a3bd-153f94c01128"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 158m,
                            Rating = 2.6448203194875175
                        },
                        new
                        {
                            Id = new Guid("acdf6b66-9fdf-4352-8d32-5b6c872fab33"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Novotel Hotel",
                            Price = 113m,
                            Rating = 3.2615209660425131
                        },
                        new
                        {
                            Id = new Guid("9922c755-3800-4f92-a49b-4ca7fa39242f"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Park Hyatt Hotel",
                            Price = 212m,
                            Rating = 3.1886608229385822
                        },
                        new
                        {
                            Id = new Guid("9e8f1ff8-5f9d-4c26-8dd7-027ca1e0378a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 376m,
                            Rating = 0.48190649143888153
                        },
                        new
                        {
                            Id = new Guid("7bf5b1d0-6ae3-4e23-885c-17c246b41866"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Peninsula Hotel",
                            Price = 296m,
                            Rating = 3.213820773426677
                        },
                        new
                        {
                            Id = new Guid("def9ee3a-c2c1-4b50-a08d-6a72a2e65c19"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 200m,
                            Rating = 3.5190963925601899
                        },
                        new
                        {
                            Id = new Guid("f6a6da35-559b-4be2-b02b-f06819a76273"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The St. Regis Hotel",
                            Price = 376m,
                            Rating = 4.2502591753913848
                        },
                        new
                        {
                            Id = new Guid("9159bbe6-e4f2-4be3-b59d-e8e9bd63e562"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Aman Hotel",
                            Price = 333m,
                            Rating = 4.51150818817435
                        },
                        new
                        {
                            Id = new Guid("dd148dda-0dd6-4251-98fe-4cf3779fe447"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Raffles Hotel",
                            Price = 350m,
                            Rating = 0.76452244439324024
                        },
                        new
                        {
                            Id = new Guid("25e6e3c5-ca60-45eb-a819-f8941a9fa996"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 292m,
                            Rating = 2.480953968134421
                        },
                        new
                        {
                            Id = new Guid("3835ba13-454e-4aaa-9bd3-127b78b62a11"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Belmond Hotel",
                            Price = 342m,
                            Rating = 0.41586485512879523
                        },
                        new
                        {
                            Id = new Guid("10315682-b8af-4a32-9092-9cbed32bdf53"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The St. Regis Hotel",
                            Price = 263m,
                            Rating = 1.6768115927331817
                        },
                        new
                        {
                            Id = new Guid("43cccdea-a156-4d4a-941c-25c77aae6bf7"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Westin Hotel",
                            Price = 385m,
                            Rating = 1.3242939385693102
                        },
                        new
                        {
                            Id = new Guid("93666af0-f6ef-4de9-b9ea-3fd2d7e7082b"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Mandarin Oriental Hotel",
                            Price = 418m,
                            Rating = 0.27966654668481306
                        },
                        new
                        {
                            Id = new Guid("c97ba8f5-c0d5-41db-b78c-094dc8fe07e0"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Sofitel Hotel",
                            Price = 480m,
                            Rating = 2.5641288050764626
                        },
                        new
                        {
                            Id = new Guid("5a2e2e2d-6385-406c-abe8-e4c9df1fc7f7"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Aman Hotel",
                            Price = 119m,
                            Rating = 2.6177745671926274
                        },
                        new
                        {
                            Id = new Guid("f683c8fd-9983-4c9c-b502-f1e6a3c83bf1"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Savoy",
                            Price = 154m,
                            Rating = 2.8229659021162234
                        },
                        new
                        {
                            Id = new Guid("6d09cb8d-a909-4ad2-a1ff-ae3103ba3ca2"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Park Hyatt Hotel",
                            Price = 437m,
                            Rating = 3.8653059856613909
                        },
                        new
                        {
                            Id = new Guid("cc9b1c96-6c10-4b53-9a4b-48ef236ac73d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Luxury Collection Hotel",
                            Price = 369m,
                            Rating = 2.0351333863377583
                        },
                        new
                        {
                            Id = new Guid("298f20d2-d7a9-4c57-9d2f-3f40a7b4081b"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Wydham Hotel",
                            Price = 348m,
                            Rating = 1.0596571342447207
                        },
                        new
                        {
                            Id = new Guid("7e9463a8-b50e-4978-bdc3-cd5cc26b0a5d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Aman Hotel",
                            Price = 137m,
                            Rating = 0.36901979221033221
                        },
                        new
                        {
                            Id = new Guid("bec413ed-9b01-4687-9615-6fa782acae3a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Aman Hotel",
                            Price = 155m,
                            Rating = 3.0522732783925295
                        },
                        new
                        {
                            Id = new Guid("b711e593-fba4-4733-ae7b-8068e868b3a6"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Sofitel Hotel",
                            Price = 383m,
                            Rating = 1.9997162572757832
                        },
                        new
                        {
                            Id = new Guid("9698de08-7a28-4feb-ab2b-590e34b5d0e6"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 223m,
                            Rating = 4.6881415519880409
                        },
                        new
                        {
                            Id = new Guid("304c020f-6764-48c1-be2a-1c3730269599"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 110m,
                            Rating = 1.6335877876507761
                        },
                        new
                        {
                            Id = new Guid("67a1f6b0-c0ff-4447-925b-968fb334a935"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Raffles Hotel",
                            Price = 331m,
                            Rating = 1.6414571781486775
                        },
                        new
                        {
                            Id = new Guid("56d470fa-f120-4656-b833-5375fea2305d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Sofitel Hotel",
                            Price = 383m,
                            Rating = 1.0418386524479812
                        },
                        new
                        {
                            Id = new Guid("2eb21fec-103f-45ae-9428-d5ddab0ef9c6"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 208m,
                            Rating = 4.560913160011733
                        },
                        new
                        {
                            Id = new Guid("a1787ef2-907f-48cd-a942-50d3ef63c375"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Four Seasons Hotel",
                            Price = 379m,
                            Rating = 1.3459474557443647
                        },
                        new
                        {
                            Id = new Guid("4d930a9b-c49a-4e54-90b6-8b290e1f1312"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 431m,
                            Rating = 0.056430175749687117
                        },
                        new
                        {
                            Id = new Guid("c5e07a9b-4ac6-40b8-a8e3-8bc9e6fe459a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Belmond Hotel",
                            Price = 222m,
                            Rating = 0.4191440892252829
                        },
                        new
                        {
                            Id = new Guid("c67a0e0a-ea0d-4a26-b1c9-84266bbf092e"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Aman Hotel",
                            Price = 343m,
                            Rating = 1.9835551254441441
                        },
                        new
                        {
                            Id = new Guid("fadf533e-a696-44c9-a31e-c12594cffff3"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Aman Hotel",
                            Price = 493m,
                            Rating = 4.9305042894758664
                        },
                        new
                        {
                            Id = new Guid("37e4062e-0496-4388-ae49-33215bc7e996"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "Hilton Hotel",
                            Price = 223m,
                            Rating = 2.327587164577432
                        },
                        new
                        {
                            Id = new Guid("6ab23088-5359-4197-9182-f0c83dfd7a63"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Luxury Collection Hotel",
                            Price = 361m,
                            Rating = 3.9964427961441067
                        },
                        new
                        {
                            Id = new Guid("889d97e5-7c26-4f8d-9cc9-3b61036723f6"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 351m,
                            Rating = 1.9625095676774551
                        },
                        new
                        {
                            Id = new Guid("52d05aad-dbda-4ab2-beaf-9df4f05f7c53"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Westin Hotel",
                            Price = 368m,
                            Rating = 2.7581180224036279
                        },
                        new
                        {
                            Id = new Guid("880ea1b7-2cb7-4c55-a402-e5117151168c"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Belmond Hotel",
                            Price = 321m,
                            Rating = 2.6868767203221458
                        },
                        new
                        {
                            Id = new Guid("95b910e8-abf6-4ae5-a17f-9e2bac2c5d9b"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 147m,
                            Rating = 1.3546786927965404
                        },
                        new
                        {
                            Id = new Guid("26c4afb5-0f91-466d-995c-ddd037ae2379"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "Four Seasons Hotel",
                            Price = 424m,
                            Rating = 0.62964295692538419
                        },
                        new
                        {
                            Id = new Guid("e9ca63e9-9ffd-4aa2-8211-d84bcadcc102"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Hyatt Hotel",
                            Price = 171m,
                            Rating = 4.2942656060575519
                        },
                        new
                        {
                            Id = new Guid("3ef86faf-a3ea-4eca-b478-a9c7f5b3257f"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Crowne Plaza Hotel",
                            Price = 191m,
                            Rating = 0.4411414763766186
                        },
                        new
                        {
                            Id = new Guid("1bdafe54-4654-498e-8c24-ccd0f92224e5"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Aman Hotel",
                            Price = 138m,
                            Rating = 2.3886312781368551
                        },
                        new
                        {
                            Id = new Guid("947d975f-8c26-4df3-bb56-ed3b60d2b2b7"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Westin Hotel",
                            Price = 387m,
                            Rating = 2.1200643741677343
                        },
                        new
                        {
                            Id = new Guid("ddb92d26-13ae-42a8-a096-2773aac8f810"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Peninsula Hotel",
                            Price = 146m,
                            Rating = 1.555313802858918
                        },
                        new
                        {
                            Id = new Guid("1f777171-e28b-413f-815d-d7029138e2ac"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 105m,
                            Rating = 4.6355124197852842
                        },
                        new
                        {
                            Id = new Guid("5af63be9-fce7-4f22-aa42-7ea751ca02b1"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Westin Hotel",
                            Price = 473m,
                            Rating = 0.17476209765484363
                        },
                        new
                        {
                            Id = new Guid("3938889b-ccc5-4ac6-8d41-601e2ec62b4d"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Park Hyatt Hotel",
                            Price = 288m,
                            Rating = 4.8830146343958223
                        },
                        new
                        {
                            Id = new Guid("24e14f65-8c93-42f9-b0c5-99d3269443e1"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Shangri-La Hotel",
                            Price = 237m,
                            Rating = 1.4898333257659069
                        },
                        new
                        {
                            Id = new Guid("43bf66f0-a4f6-4b30-8091-57035dfc2f5c"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "The Fairmont Hotel",
                            Price = 274m,
                            Rating = 4.7361755713110814
                        },
                        new
                        {
                            Id = new Guid("6aa30a1d-0acb-441e-99ae-bc03e7e72fc7"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 161m,
                            Rating = 2.411906994248016
                        },
                        new
                        {
                            Id = new Guid("8a5dfff1-efb3-47ae-a63d-78c1dd4b972b"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Shangri-La Hotel",
                            Price = 402m,
                            Rating = 3.4571681778416528
                        },
                        new
                        {
                            Id = new Guid("8abecd2c-51f6-458e-b6fe-efea00681a63"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Rosewood Hotel",
                            Price = 167m,
                            Rating = 3.1980276845811768
                        },
                        new
                        {
                            Id = new Guid("ae27ea83-51c4-4eb4-a64f-a15fea3691de"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage5.jpg",
                            Name = "Sheraton Hotel",
                            Price = 347m,
                            Rating = 4.8154301218481033
                        },
                        new
                        {
                            Id = new Guid("1e0ba401-9eb8-454c-9f46-50eb94520ba5"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage3.jpg",
                            Name = "The Mandarin Hotel",
                            Price = 221m,
                            Rating = 3.2070255464816526
                        },
                        new
                        {
                            Id = new Guid("d422784d-8d9c-46a4-a1f6-baf814fefeb0"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Mandarin Hotel",
                            Price = 113m,
                            Rating = 1.1486088723780634
                        },
                        new
                        {
                            Id = new Guid("90818a8f-99e3-47b9-ad5d-23ed2bc0c4d2"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "Grand Hotel",
                            Price = 204m,
                            Rating = 2.8027834909100973
                        },
                        new
                        {
                            Id = new Guid("64f27b9c-69b1-44fe-8430-d021f0ebf59a"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 127m,
                            Rating = 0.98387639044586139
                        },
                        new
                        {
                            Id = new Guid("f7c9895b-d1c6-4a33-a3a1-cf8d560e3d16"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "New York",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Oberoi Hotel",
                            Price = 130m,
                            Rating = 4.8572405264996421
                        },
                        new
                        {
                            Id = new Guid("56d292c2-4458-429e-939e-4d050db4893e"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Sydney",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Hyatt Hotel",
                            Price = 381m,
                            Rating = 2.971903382872326
                        },
                        new
                        {
                            Id = new Guid("d198a1cd-2084-47d5-80d8-840031d85c47"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage2.jpg",
                            Name = "The Radisson Hotel",
                            Price = 428m,
                            Rating = 1.3455270738867131
                        },
                        new
                        {
                            Id = new Guid("af62554e-4ea8-4607-a12c-c7a5cd7ce241"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Paris",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The Crowne Plaza Hotel",
                            Price = 369m,
                            Rating = 4.2483525474083628
                        },
                        new
                        {
                            Id = new Guid("19cbe83f-5aca-4e0b-a59c-ec0b78cfd482"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "Tokyo",
                            MainImageUrl = "mainimage1.jpg",
                            Name = "The Banyan Tree Hotel",
                            Price = 140m,
                            Rating = 3.2437035286509279
                        },
                        new
                        {
                            Id = new Guid("fb39f680-6717-4c96-a3b5-34144cce1a26"),
                            ImageUrls = "System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]",
                            Location = "London",
                            MainImageUrl = "mainimage4.jpg",
                            Name = "The St. Regis Hotel",
                            Price = 353m,
                            Rating = 1.9571988992406557
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
